/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import civitas.*;

/**
 *
 * @author antonio
 */
public class CasillaPanel extends javax.swing.JPanel {
    
    Casilla casilla;

    public CasillaPanel() {
        initComponents();
    }
    
    public void setJugadoresCasilla(Casilla c) {
        this.casilla = c;
        nombre.setText(casilla.getNombre());
        // Se elimina la información antigua
        jugadoresCasilla.removeAll();
        // Se recorre la lista de propiedades para ir creando sus vistas individuales y añadirlas al panel
        for (Jugador j : casilla.getJugadores()) {
            JugadorEnCasillaPanel jug_panel = new JugadorEnCasillaPanel();
            jug_panel.setNombreJugador(j);
            jugadoresCasilla.add(jug_panel);
            jug_panel.setVisible(true);
        }
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jugadoresCasilla = new javax.swing.JPanel();

        jLabel1.setText("Calle:");
        add(jLabel1);

        nombre.setEditable(false);
        nombre.setText("calle");
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        add(nombre);

        jLabel3.setText("Jugadores:");
        add(jLabel3);

        jugadoresCasilla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jugadoresCasilla);
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jugadoresCasilla;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
