/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.util.ArrayList;
import civitas.*;

/**
 *
 * @author antonio
 */
public class JugadorPanel extends javax.swing.JPanel {
    
    private Jugador jugador;
    
    /**
     * Creates new form JugadorPanel
     */
    public JugadorPanel() {
        initComponents();
    }

    public void setJugador(Jugador j) {
        this.jugador = j;
        nombre.setText(jugador.getNombre());
        saldo.setText(Float.toString(jugador.getSaldo()));
        if (jugador.getEspeculador()) {
            especulador.setText("Sí");
        } else {
            especulador.setText("No");
        }
        rellenaPropiedades(jugador.getPropiedades());
        repaint();
        revalidate();
    }
    
    private void rellenaPropiedades (ArrayList<CasillaCalle> lista) {
        // Se elimina la información antigua
        propiedadesPanel.removeAll();
        // Se recorre la lista de propiedades para ir creando sus vistas individuales y añadirlas al panel
        for (CasillaCalle t : lista) {
            PropiedadPanel vistaPropiedad = new PropiedadPanel();
            vistaPropiedad.setPropiedad(t);
            propiedadesPanel.add(vistaPropiedad);
            vistaPropiedad.setVisible(true);
        }
        // Se fuerza la actualización visual del panel propiedades y del panel del jugador
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        saldo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        especulador = new javax.swing.JTextField();
        propiedadesPanel = new javax.swing.JPanel();

        jLabel1.setText("Nombre:");
        add(jLabel1);

        nombre.setEditable(false);
        nombre.setText("Nombre");
        add(nombre);

        jLabel2.setText("Saldo:");
        add(jLabel2);

        saldo.setEditable(false);
        saldo.setText("Saldo");
        saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoActionPerformed(evt);
            }
        });
        add(saldo);

        jLabel3.setText("Especulador:");
        add(jLabel3);

        especulador.setEditable(false);
        especulador.setText("Especulador");
        especulador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especuladorActionPerformed(evt);
            }
        });
        add(especulador);

        propiedadesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(propiedadesPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldoActionPerformed

    private void especuladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especuladorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especuladorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField especulador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nombre;
    private javax.swing.JPanel propiedadesPanel;
    private javax.swing.JTextField saldo;
    // End of variables declaration//GEN-END:variables
}
